
version: '2.1'

networks:
  normsup:
    name: normsup

services:

  client.normsup:
    extends:
      file: compose-default.yml
      service: client_build
    command: ng serve --host 0.0.0.0 --disable-host-check --watch --poll=1000
    container_name: client.normsup
    volumes:
      - ./front/src:/usr/src/app/src
      - ./front/angular.json:/usr/src/app/angular.json
      - ./front/tslint.json:/usr/src/app/tslint.json
      - ./front/config/environment.local.ts:/usr/src/app/src/app/config/environment.ts
    ports:
      - 4200:4200
    networks:
      - normsup

