
version: '2.1'

networks:
  normsup:
    name: normsup

services:

  server.normsup:
    extends:
      file: compose-default.yml
      service: server_build
    container_name: server.normsup
    restart: always
    command: bash -c "(grunt build && npm run deploy;) && grunt"
    environment:
      NODE_ENV: 'local'
      TZ: 'Europe/Paris' 
      PORT: 8080
    volumes:
      - ./back/server:/usr/src/app/server
      - ./back/tsconfig.json:/usr/src/app/tsconfig.json # TS filenames get added automatically to this file on build
    ports:
      - 8080:8080 # API
      - 127.0.0.1:5858:5858 # Debug
    networks:
      - normsup

  database.normsup:
    extends:
      file: compose-default.yml
      service: mysql_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: database.normsup
    environment:
      TZ: Europe/Paris
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: normsup
      MYSQL_USER: admin
      MYSQL_PASSWORD: Jesuisla1!
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/migrations:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:3307:3307
    expose:
      - 3307
    networks:
      - normsup
