
version: '2.1'

networks:
  normsup:
    name: normsup

services:

  server.normsup:
    extends:
      file: compose-default.yml
      service: server_build
    container_name: server.normsup
    command: bash -c "(grunt build && npm run deploy;) && grunt"
    environment:
      PORT: 8080
      NODE_ENV: prod
    volumes:
      - ./back/server:/usr/src/app/server
      - ./back/tsconfig.json:/usr/src/app/tsconfig.json # TS filenames get added automatically to this file on build
    ports:
      - 8080:8080 # API
      - 127.0.0.1:5858:5858 # Debug
    networks:
      - normsup

  # client.normsup:
  #   extends:
  #     file: compose-default.yml
  #     service: client_build
  #   command: ng serve --host 0.0.0.0 --disable-host-check --watch --poll=1000
  #   container_name: client.normsup
  #   volumes:
  #     - ./front/src:/usr/src/app/src
  #     - ./front/angular.json:/usr/src/app/angular.json
  #     - ./front/tslint.json:/usr/src/app/tslint.json
  #     - ./front/config/environment.local.ts:/usr/src/app/src/app/config/environment.ts
  #   ports:
  #     - 4200:4200
  #   networks:
  #     - normsup

  database.normsup:
    extends:
      file: compose-default.yml
      service: mysql_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: database.normsup
    environment:
      TZ: Europe/Paris
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: normsup
      MYSQL_USER: admin
      MYSQL_PASSWORD: Jesuisla1!
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/migrations:/docker-entrypoint-initdb.d
    ports:
      - 3307:3307
    expose:
      - 3307
    networks:
      - normsup
