// TODO get gender
// TODO get custom DOCUMENTS to request

export const email = '<div style="color: #333;"> <img src="https://normsup.s3-eu-west-1.amazonaws.com/normsup-logo.png" width="100" height="100" /> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <span>Votre client <%= client_name %> nous a mandaté afin que de récolter les documents KBIS, URSSAF et LNTE de votre société <%= denomination %>. <br /> Pour cela, il suffit de vous rendre sur notre plateforme dédiée en cliquant sur le lien ci dessous et d’y déposer votre document en moins de deux minutes.</span> </p> <br /> <br /> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/supplier/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://normsup.com">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

export const supplierUserEmail = '<div style="color: #333;"> <img src="https://normsup.s3-eu-west-1.amazonaws.com/normsup-logo.png" width="100" height="100" /><p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <span>Votre client <%= client_name %> nous a mandaté afin que de récolter les documents de votre société <%= denomination %>. <br /> Pour cela, il suffit de vous rendre sur notre plateforme dédiée en cliquant sur le lien ci dessous et d’y déposer votre document en moins de deux minutes.</span> </p> <br /> <br /> <p> <span>Voici vos identifiants afin de vous connecter à notre plateforme. </span> <br /> <br /> <br /> <span style="padding-left: 30px;">Email : <%= login %></span> <br /> <span style="padding-left: 30px;">Mot de passe : <%= password %></span> </p> <br /> <br /> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/supplier/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://normsup.com">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

export const activationMail = '<div style="color: #333;"> <img src="https://normsup.s3-eu-west-1.amazonaws.com/normsup-logo.png" width="100" height="100" /> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <span>Un compte vous a été octroyé sur notre plateforme NormSup. </span> <br /> <span>Activez votre compte en cliquant sur le bouton suivant:</span> </p> <br /> <br /> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="<%- link%>" style="color: white;text-align: center;"> Cliquez ici</a> </button> </div> <br /> <div>Vous pouvez également cliquer sur ce lien afin d\'activer votre compte : <%- link%> </div> <br /> <br /> <div>Pour vous aider dans vos démarches, découvrez nos articles dédiés en cliquant <a href="https://normsup.com">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

export const duplicateSupplier = '<div style="color: #333;"> <img src="https://normsup.s3-eu-west-1.amazonaws.com/normsup-logo.png" width="100" height="100" /><p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <span>Votre client <%= client_name %> nous a mandaté afin que de récolter les documents de votre société <%= denomination %>. <br/> Pour cela, il suffit de vous rendre sur notre plateforme dédiée en cliquant sur le lien ci dessous et d’y déposer votre document en moins de deux minutes.</span> </p> <br /> <br /> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/supplier/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://normsup.com">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';