
// NOTTODATE - INVALID MAIL - OFFLINE 
export const alertMail_0 = '<div style="color: #333;"> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <span>Voici votre récapitulatif de conformité fournisseur :</span> <br/> <span> Vous avez <span><%= invalidMail %></span> fournisseurs avec un email invalide. </span> <br/> <span> Vous avez <span><%= notToDate %></span> fournisseurs non à jour sur un total de <span><%= totalSuppliers %></span>. </span> <br/> <span> Vous avez <span><%= offline %></span> fournisseurs hors ligne sur un total de <span><%= totalSuppliers %></span>. </span> <br/> </p> <br/> <br/> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://app.normsup.com/login">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

// NOTTODATE - INVALID MAIL 
export const alertMail_1 = '<div style="color: #333;"> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <br/> <br/> <span>Voici votre récapitulatif de conformité fournisseur :</span> <br/> <span> Vous avez <span><%= invalidMail %></span> fournisseurs avec un email invalide. </span> <br/> <span> Vous avez <span><%= notToDate %></span> fournisseurs non à jour sur un total de <span><%= totalSuppliers %></span>. </span> <br/> <br/> </p> <br/> <br/> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://app.normsup.com/login">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

// NOTTODATE - OFFLINE 
export const alertMail_2 = '<div style="color: #333;"> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <br/><br/> <span>Voici votre récapitulatif de conformité fournisseur :</span> <br/> <br/> <span> Vous avez <span><%= notToDate %></span> fournisseurs non à jour sur un total de <span><%= totalSuppliers %></span>. </span> <br/> <br/> <span> Vous avez <span><%= offline %></span> fournisseurs hors ligne sur un total de <span><%= totalSuppliers %></span>. </span> <br/> <br/> </p> <br/> <br/> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://app.normsup.com/login">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

// INVALID MAIL - OFFLINE
export const alertMail_3 = '<div style="color: #333;"> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <br/><br/> <span>Voici votre récapitulatif de conformité fournisseur :</span> <br/> <br/> <span> Vous avez <span><%= invalidMail %></span> fournisseurs avec un email invalide. </span> <br/> <br/> <span> Vous avez <span><%= offline %></span> fournisseurs hors ligne sur un total de <span><%= totalSuppliers %></span>. </span> <br/> <br/> </p> <br/> <br/> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://app.normsup.com/login">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

// INVALID MAIL 
export const alertMail_4 = '<div style="color: #333;"> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <br/><br/> <span>Voici votre récapitulatif de conformité fournisseur :</span> <br/> <br/> <span> Vous avez <span><%= invalidMail %></span> fournisseurs avec un email invalide. </span> <br/> <br/> </p> <br/> <br/> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://app.normsup.com/login">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

//  OFFLINE
export const alertMail_5 = '<div style="color: #333;"> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <br/><br/> <span>Voici votre récapitulatif de conformité fournisseur :</span> <br/> <br/> <span> Vous avez <span><%= offline %></span> fournisseurs hors ligne sur un total de <span><%= totalSuppliers %></span>. </span> <br/> <br/> </p> <br/> <br/> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://app.normsup.com/login">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';

// NOTTODATE
export const alertMail_6 = '<div style="color: #333;"> <p>Bonjour <%= rTitle %> <%= respresName %>,</p> <p> <br/><br/> <span>Voici votre récapitulatif de conformité fournisseur :</span> <br/> <br/> <span> Vous avez <span><%= notToDate %></span> fournisseurs non à jour sur un total de <span><%= totalSuppliers %></span>. </span> <br/> <br/> </p> <br/> <br/> <div style="max-width: 450px;"> <button style="margin: 0 auto;display: block;border:none;width: 130px;padding: 5px 0px;background-color: #4390EF;border-radius: 5px;"> <a href="https://app.normsup.com/login" style="color: white;text-align: center;"> Accéder à votre <br /> Espace Fournisseur </a> </button> </div> <br /> <br /> <div>Pour vous aider dans cette démarches, découvrez notre article dédié en cliquant <a href="https://app.normsup.com/login">ici</a>. </div> <br /> <div style="width: 100%;">Bien cordialement,</div> <div style="width: 100%;">L’équipe NormSup</div> </div>';