---
development:
  cloud_name: dfvfietwv
  api_key: '418133981835592'
  api_secret: fo4tvFRTVzV7nS1ETLYV3gtCaxY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dfvfietwv
  api_key: '418133981835592'
  api_secret: fo4tvFRTVzV7nS1ETLYV3gtCaxY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dfvfietwv
  api_key: '418133981835592'
  api_secret: fo4tvFRTVzV7nS1ETLYV3gtCaxY
  enhance_image_tag: true
  static_image_support: false
