AdminUser.create!([
  {email: "e.derozin@gmail.com", password: 'e.derozin@gmail.com', reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil}
])
Company.create!([
  {name: "orange", siret: "92343843284", invalid_at: "2018-11-29 07:34:23", valid_at: nil, is_valid: false, kbis: nil, urssaf: nil, lnte: nil, rails: nil, g: nil, migration: nil, add_fields_to_company: nil, efetcent: nil, l6_declaree: nil, l6_normalisee: nil, libtefen: nil, iriset: nil, libcom: nil, typvoie: nil, dapet: nil, dcren: nil, l1_normalisee: nil, epci: nil, ddebact: nil, categorie: nil, tcd: nil, modet: nil, libtefet: nil, proden: nil, libtu: nil, siren: nil, nom_dept: nil, defet: nil, apet700: nil, depcomet: nil, section: nil, tu: nil, libvoie: nil, defen: nil, libapet: nil, depcomen: nil, amintret: nil, code_section: nil, l4_normalisee: nil, prodet: nil, libactivnat: nil, nomen_long: nil, codpos: nil, monoact: nil, code_classe: nil, l4_declaree: nil, amintren: nil, apen700: nil, siege: nil, nic: nil, tefet: nil, libreg_new: nil, nj: nil, libmonoact: nil, numvoie: nil, nicsiege: nil, libmodet: nil, libmoden: nil, lieuact: nil, diffcom: nil, dcret: nil, du: nil, coordonnees: nil, depet: nil, code_division: nil, code_groupe: nil, datemaj: nil, dapen: nil, l7_normalisee: nil, l1_declaree: nil, activnat: nil, uu: nil, activite: nil, libnj: nil, tefen: nil, efencent: nil, rpen: nil, origine: nil, libapen: nil, zemet: nil, arronet: nil, saisonat: nil, rpet: nil, sous_classe: nil, moden: nil, comet: nil, auxilt: nil, ind_publipo: nil, liborigine: nil},
  {name: "Allocakes", siret: "848384234", invalid_at: "2018-11-29 07:34:23", valid_at: nil, is_valid: false, kbis: nil, urssaf: nil, lnte: nil, rails: nil, g: nil, migration: nil, add_fields_to_company: nil, efetcent: nil, l6_declaree: nil, l6_normalisee: nil, libtefen: nil, iriset: nil, libcom: nil, typvoie: nil, dapet: nil, dcren: nil, l1_normalisee: nil, epci: nil, ddebact: nil, categorie: nil, tcd: nil, modet: nil, libtefet: nil, proden: nil, libtu: nil, siren: nil, nom_dept: nil, defet: nil, apet700: nil, depcomet: nil, section: nil, tu: nil, libvoie: nil, defen: nil, libapet: nil, depcomen: nil, amintret: nil, code_section: nil, l4_normalisee: nil, prodet: nil, libactivnat: nil, nomen_long: nil, codpos: nil, monoact: nil, code_classe: nil, l4_declaree: nil, amintren: nil, apen700: nil, siege: nil, nic: nil, tefet: nil, libreg_new: nil, nj: nil, libmonoact: nil, numvoie: nil, nicsiege: nil, libmodet: nil, libmoden: nil, lieuact: nil, diffcom: nil, dcret: nil, du: nil, coordonnees: nil, depet: nil, code_division: nil, code_groupe: nil, datemaj: nil, dapen: nil, l7_normalisee: nil, l1_declaree: nil, activnat: nil, uu: nil, activite: nil, libnj: nil, tefen: nil, efencent: nil, rpen: nil, origine: nil, libapen: nil, zemet: nil, arronet: nil, saisonat: nil, rpet: nil, sous_classe: nil, moden: nil, comet: nil, auxilt: nil, ind_publipo: nil, liborigine: nil},
  {name: "Dauré", siret: nil, invalid_at: "2018-11-29 07:34:23", valid_at: nil, is_valid: false, kbis: nil, urssaf: nil, lnte: nil, rails: nil, g: nil, migration: nil, add_fields_to_company: nil, efetcent: nil, l6_declaree: nil, l6_normalisee: nil, libtefen: nil, iriset: nil, libcom: nil, typvoie: nil, dapet: nil, dcren: nil, l1_normalisee: nil, epci: nil, ddebact: nil, categorie: nil, tcd: nil, modet: nil, libtefet: nil, proden: nil, libtu: nil, siren: nil, nom_dept: nil, defet: nil, apet700: nil, depcomet: nil, section: nil, tu: nil, libvoie: nil, defen: nil, libapet: nil, depcomen: nil, amintret: nil, code_section: nil, l4_normalisee: nil, prodet: nil, libactivnat: nil, nomen_long: nil, codpos: nil, monoact: nil, code_classe: nil, l4_declaree: nil, amintren: nil, apen700: nil, siege: nil, nic: nil, tefet: nil, libreg_new: nil, nj: nil, libmonoact: nil, numvoie: nil, nicsiege: nil, libmodet: nil, libmoden: nil, lieuact: nil, diffcom: nil, dcret: nil, du: nil, coordonnees: nil, depet: nil, code_division: nil, code_groupe: nil, datemaj: nil, dapen: nil, l7_normalisee: nil, l1_declaree: nil, activnat: nil, uu: nil, activite: nil, libnj: nil, tefen: nil, efencent: nil, rpen: nil, origine: nil, libapen: nil, zemet: nil, arronet: nil, saisonat: nil, rpet: nil, sous_classe: nil, moden: nil, comet: nil, auxilt: nil, ind_publipo: nil, liborigine: nil},
  {name: "R D CLICK", siret: "81834075400014", invalid_at: "2018-11-29 07:34:23", valid_at: nil, is_valid: false, kbis: nil, urssaf: nil, lnte: nil, rails: nil, g: nil, migration: nil, add_fields_to_company: nil, efetcent: "NN", l6_declaree: "75008 PARIS 8", l6_normalisee: "75008 PARIS", libtefen: "00 - 0 salarié", iriset: "751083103", libcom: "PARIS 8", typvoie: "RUE", dapet: "2016", dcren: "2016-02-05", l1_normalisee: "R D CLICK", epci: "200054781", ddebact: "2016-02-05", categorie: "Non renseignée", tcd: "80", modet: "S", libtefet: "00 - 0 salarié", proden: "Productif", libtu: "Agglomération de Paris", siren: "818340754", nom_dept: "PARIS", defet: "2016", apet700: "4791B", depcomet: "75108", section: "Commerce ; réparation d'automobiles et de motocycles", tu: "8", libvoie: "DE PENTHIEVRE", defen: "2016", libapet: "Vente à distance sur catalogue spécialisé", depcomen: "75108", amintret: "2016-02", code_section: "G", l4_normalisee: "10 RUE DE PENTHIEVRE", prodet: "Productif", libactivnat: "Services", nomen_long: "R.D CLICK", codpos: "75008", monoact: "1", code_classe: "4791", l4_declaree: "10 RUE DE PENTHIEVRE", amintren: "2016-02", apen700: "4791B", siege: "Etablissement siège", nic: "00014", tefet: "00", libreg_new: "Ile-de-France", nj: "5710", libmonoact: "Entreprise dont tous les établissements ont la même activité principale", numvoie: "10", nicsiege: "00014", libmodet: "Activité simple", libmoden: "Activité simple", lieuact: "07", diffcom: "Établissement diffusable", dcret: "2016-02-05", du: "00", coordonnees: "[48.873054, 2.316593]", depet: "75", code_division: "470", code_groupe: "479", datemaj: "2016-02-11T00:00:00+00:00", dapen: "2016", l7_normalisee: "FRANCE", l1_declaree: "R.D CLICK", activnat: "12", uu: "51", activite: "Commerce ; réparation d'automobiles et de motocycles / Vente à distance sur catalogue spécialis", libnj: "SAS, société par actions simplifiée", tefen: "00", efencent: "NN", rpen: "11", origine: "1", libapen: "Vente à distance sur catalogue spécialisé", zemet: "1101", arronet: "1", saisonat: "Permanente", rpet: "11", sous_classe: "Vente à distance sur catalogue spécialis", moden: "S", comet: "108", auxilt: "Non auxiliaire", ind_publipo: "établissement faisant partie du champ du publipostage", liborigine: "Création (pour tout type de déclaration)"}
])
UserRole.create!([
  {name: "Admin", slug: nil},
  {name: "Éditeur", slug: nil},
  {name: "Invité", slug: nil}
])

User.create!([
  {email: "e.derozin@gmail.com", password: 'e.derozin@gmail.com', reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: "2018-11-29 07:35:00", sign_in_count: 6, current_sign_in_at: "2018-11-29 07:35:00", last_sign_in_at: "2018-11-28 16:03:21", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", company_id: 3, first_name: "", last_name: "", parent_id: nil, user_role_id: nil, user_role_id: 1}
])
Supplier.create!([
  {user_id: 1, company_id: 1},
  {user_id: 1, company_id: 2},
  {user_id: 1, company_id: 4}
])
Interlocutor.create!([
  {first_name: "test", last_name: "test", man: false, email: "test", position: "", privileged: true, company_id: 1, supplier_id: 1},
  {first_name: "test 2", last_name: "test 2", man: false, email: "test 2", position: "", privileged: true, company_id: 1, supplier_id: 1}
])
