class AddFieldsToCompany < ActiveRecord::Migration[5.1]
  def change
    add_column :companies, :rails, :string
    add_column :companies, :g, :string
    add_column :companies, :migration, :string
    add_column :companies, :add_fields_to_company, :string
    add_column :companies, :efetcent, :string
    add_column :companies, :l6_declaree, :string
    add_column :companies, :l6_normalisee, :string
    add_column :companies, :libtefen, :string
    add_column :companies, :iriset, :string
    add_column :companies, :libcom, :string
    add_column :companies, :typvoie, :string
    add_column :companies, :dapet, :string
    add_column :companies, :dcren, :string
    add_column :companies, :l1_normalisee, :string
    add_column :companies, :epci, :string
    add_column :companies, :ddebact, :string
    add_column :companies, :categorie, :string
    add_column :companies, :tcd, :string
    add_column :companies, :modet, :string
    add_column :companies, :libtefet, :string
    add_column :companies, :proden, :string
    add_column :companies, :libtu, :string
    add_column :companies, :siren, :string
    add_column :companies, :nom_dept, :string
    add_column :companies, :defet, :string
    add_column :companies, :apet700, :string
    add_column :companies, :depcomet, :string
    add_column :companies, :section, :string
    add_column :companies, :tu, :string
    add_column :companies, :libvoie, :string
    add_column :companies, :defen, :string
    add_column :companies, :libapet, :string
    add_column :companies, :depcomen, :string
    add_column :companies, :amintret, :string
    add_column :companies, :code_section, :string
    add_column :companies, :l4_normalisee, :string
    add_column :companies, :prodet, :string
    add_column :companies, :libactivnat, :string
    add_column :companies, :nomen_long, :string
    add_column :companies, :codpos, :string
    add_column :companies, :monoact, :string
    add_column :companies, :code_classe, :string
    add_column :companies, :l4_declaree, :string
    add_column :companies, :amintren, :string
    add_column :companies, :apen700, :string
    add_column :companies, :siege, :string
    add_column :companies, :nic, :string
    add_column :companies, :tefet, :string
    add_column :companies, :libreg_new, :string
    add_column :companies, :nj, :string
    add_column :companies, :libmonoact, :string
    add_column :companies, :numvoie, :string
    add_column :companies, :nicsiege, :string
    add_column :companies, :libmodet, :string
    add_column :companies, :libmoden, :string
    add_column :companies, :lieuact, :string
    add_column :companies, :diffcom, :string
    add_column :companies, :dcret, :string
    add_column :companies, :du, :string
    add_column :companies, :coordonnees, :string
    add_column :companies, :depet, :string
    add_column :companies, :code_division, :string
    add_column :companies, :code_groupe, :string
    add_column :companies, :datemaj, :string
    add_column :companies, :dapen, :string
    add_column :companies, :l7_normalisee, :string
    add_column :companies, :l1_declaree, :string
    add_column :companies, :activnat, :string
    add_column :companies, :uu, :string
    add_column :companies, :activite, :string
    add_column :companies, :libnj, :string
    add_column :companies, :tefen, :string
    add_column :companies, :efencent, :string
    add_column :companies, :rpen, :string
    add_column :companies, :origine, :string
    add_column :companies, :libapen, :string
    add_column :companies, :zemet, :string
    add_column :companies, :arronet, :string
    add_column :companies, :saisonat, :string
    add_column :companies, :rpet, :string
    add_column :companies, :sous_classe, :string
    add_column :companies, :moden, :string
    add_column :companies, :comet, :string
    add_column :companies, :auxilt, :string
    add_column :companies, :ind_publipo, :string
    add_column :companies, :liborigine, :string
    change_column :companies, :siret, :string
  end
end
